import sqlite3

name = "fdhv9"
sequence = "MKIVLVLYDAGKHAADEEKLYGCTENKLGIANWLKDQGHELITTSDKEGGNSVLDQHIPDADIIITTPFHPAYITKERIDKAKKLKLVVVAGVGSDHIDLDYINQTGKKISVLEVTGSNVVSVAEHVLMTMLVLVRNFVPAHEQIINHDWEVAAIAKDAYDIEGKTIATIGAGRIGYRVLERLVPFNPKELLYYDYQALPKDAEEKVGARRVENIEELVAQADIVTINAPLHAGTKGLINKELLSKFKKGAWLVNTARGAICVAEDVAAALESGQLRGYGGDVWFPQPAPKDHPWRDMRNKYGAGNAMTPHYSGTTLDAQTRYAEGTKNILESFFTGKFDYRPQDIILLNGEYITKAYGKHDKK"


conn = sqlite3.connect('./database/protein.db')
cur = conn.cursor()

cur.execute("INSERT INTO proteins (name, sequence) VALUES (?, ?)", (name, sequence))


conn.commit()
conn.close()
